// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright © 2014
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace NCop.Mixins.Exceptions
{
	[Serializable]
	public class MissingFieldBuilderException : ArgumentException
	{
		private static string message = "Missing field Builder";
		
		public MissingFieldBuilderException(string message = null) : base(message ?? MissingFieldBuilderException.message) { }

		public MissingFieldBuilderException(Exception innerException) : this(message, innerException) { }

		public MissingFieldBuilderException(string parameterName, string message = null) : base(message ?? MissingFieldBuilderException.message, parameterName) { }

		public MissingFieldBuilderException(string message, Exception innerException) : base(message, innerException) { }

		protected MissingFieldBuilderException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	