// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright © 2014
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------
using System;
using NCop.Aspects.Engine;
using NCop.Aspects.Framework;
using System.Collections.Generic;

namespace NCop.Aspects.Extensions
{
	internal static class AspectArgsContractResolver
	{
		private static readonly IDictionary<int, Type> funcArgsMap = null;
		private static readonly IDictionary<int, Type> actionArgsMap = null;

		static AspectArgsContractResolver() {
			funcArgsMap = new Dictionary<int, Type>();
			actionArgsMap = new Dictionary<int, Type>();

			funcArgsMap.Add(1, typeof(IFunctionArgs<>));	
			actionArgsMap.Add(1, typeof(IActionArgs<>));	

			funcArgsMap.Add(2, typeof(IFunctionArgs<,>));	
			actionArgsMap.Add(2, typeof(IActionArgs<,>));	

			funcArgsMap.Add(3, typeof(IFunctionArgs<,,>));	
			actionArgsMap.Add(3, typeof(IActionArgs<,,>));	

			funcArgsMap.Add(4, typeof(IFunctionArgs<,,,>));	
			actionArgsMap.Add(4, typeof(IActionArgs<,,,>));	

			funcArgsMap.Add(5, typeof(IFunctionArgs<,,,,>));	
			actionArgsMap.Add(5, typeof(IActionArgs<,,,,>));	

			funcArgsMap.Add(6, typeof(IFunctionArgs<,,,,,>));	
			actionArgsMap.Add(6, typeof(IActionArgs<,,,,,>));	

			funcArgsMap.Add(7, typeof(IFunctionArgs<,,,,,,>));	
			actionArgsMap.Add(7, typeof(IActionArgs<,,,,,,>));	

			funcArgsMap.Add(8, typeof(IFunctionArgs<,,,,,,,>));	
			actionArgsMap.Add(8, typeof(IActionArgs<,,,,,,,>));	
		}

		internal static Type ToFunctionAspectArgument(this Type[] typeArguments) {
			return funcArgsMap[typeArguments.Length].MakeGenericType(typeArguments);
		}
		
		internal static Type ToActionAspectArgument(this Type[] typeArguments) {
			return actionArgsMap[typeArguments.Length].MakeGenericType(typeArguments);
		}	
	}
}