// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright ©
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace NCop.Aspects.Extensions
{
	using System;
	using System.Reflection;
	using NCop.Aspects.Engine;
	using NCop.Core.Extensions;
	using System.Collections.Generic;

	internal static class AspectArgsImplResolver
	{
		internal static readonly IDictionary<int, Type> FuncEventArgsMap = null;
		internal static readonly IDictionary<int, Type> ActionEventArgsMap = null;
		internal static readonly IDictionary<int, Type> FuncExecutionArgsMap = null;
		internal static readonly IDictionary<int, Type> ActionExecutionArgsMap = null;
		internal static readonly IDictionary<int, Type> FuncInterceptionArgsMap = null;
		internal static readonly IDictionary<int, Type> ActionInterceptionArgsMap = null;

		static AspectArgsImplResolver() {
			FuncEventArgsMap = new Dictionary<int, Type>();
			ActionEventArgsMap = new Dictionary<int, Type>();
			FuncExecutionArgsMap = new Dictionary<int, Type>();
			ActionExecutionArgsMap = new Dictionary<int, Type>();
			FuncInterceptionArgsMap = new Dictionary<int, Type>();
			ActionInterceptionArgsMap = new Dictionary<int, Type>();

			ActionExecutionArgsMap.Add(0, typeof(ActionExecutionArgsImpl<>));	
			ActionInterceptionArgsMap.Add(0, typeof(ActionInterceptionArgsImpl<>));

			FuncExecutionArgsMap.Add(1, typeof(FunctionExecutionArgsImpl<,>));	
			ActionExecutionArgsMap.Add(1, typeof(ActionExecutionArgsImpl<,>));	
			FuncEventArgsMap.Add(1, typeof(EventFunctionInterceptionArgsImpl<,>));
			ActionEventArgsMap.Add(1, typeof(EventActionInterceptionArgsImpl<,>));
			ActionInterceptionArgsMap.Add(1, typeof(ActionInterceptionArgsImpl<,>));	
			FuncInterceptionArgsMap.Add(1, typeof(FunctionInterceptionArgsImpl<,>));							

			FuncExecutionArgsMap.Add(2, typeof(FunctionExecutionArgsImpl<,,>));	
			ActionExecutionArgsMap.Add(2, typeof(ActionExecutionArgsImpl<,,>));	
			FuncEventArgsMap.Add(2, typeof(EventFunctionInterceptionArgsImpl<,,>));
			ActionEventArgsMap.Add(2, typeof(EventActionInterceptionArgsImpl<,,>));
			ActionInterceptionArgsMap.Add(2, typeof(ActionInterceptionArgsImpl<,,>));	
			FuncInterceptionArgsMap.Add(2, typeof(FunctionInterceptionArgsImpl<,,>));							

			FuncExecutionArgsMap.Add(3, typeof(FunctionExecutionArgsImpl<,,,>));	
			ActionExecutionArgsMap.Add(3, typeof(ActionExecutionArgsImpl<,,,>));	
			FuncEventArgsMap.Add(3, typeof(EventFunctionInterceptionArgsImpl<,,,>));
			ActionEventArgsMap.Add(3, typeof(EventActionInterceptionArgsImpl<,,,>));
			ActionInterceptionArgsMap.Add(3, typeof(ActionInterceptionArgsImpl<,,,>));	
			FuncInterceptionArgsMap.Add(3, typeof(FunctionInterceptionArgsImpl<,,,>));							

			FuncExecutionArgsMap.Add(4, typeof(FunctionExecutionArgsImpl<,,,,>));	
			ActionExecutionArgsMap.Add(4, typeof(ActionExecutionArgsImpl<,,,,>));	
			FuncEventArgsMap.Add(4, typeof(EventFunctionInterceptionArgsImpl<,,,,>));
			ActionEventArgsMap.Add(4, typeof(EventActionInterceptionArgsImpl<,,,,>));
			ActionInterceptionArgsMap.Add(4, typeof(ActionInterceptionArgsImpl<,,,,>));	
			FuncInterceptionArgsMap.Add(4, typeof(FunctionInterceptionArgsImpl<,,,,>));							

			FuncExecutionArgsMap.Add(5, typeof(FunctionExecutionArgsImpl<,,,,,>));	
			ActionExecutionArgsMap.Add(5, typeof(ActionExecutionArgsImpl<,,,,,>));	
			FuncEventArgsMap.Add(5, typeof(EventFunctionInterceptionArgsImpl<,,,,,>));
			ActionEventArgsMap.Add(5, typeof(EventActionInterceptionArgsImpl<,,,,,>));
			ActionInterceptionArgsMap.Add(5, typeof(ActionInterceptionArgsImpl<,,,,,>));	
			FuncInterceptionArgsMap.Add(5, typeof(FunctionInterceptionArgsImpl<,,,,,>));							

			FuncExecutionArgsMap.Add(6, typeof(FunctionExecutionArgsImpl<,,,,,,>));	
			ActionExecutionArgsMap.Add(6, typeof(ActionExecutionArgsImpl<,,,,,,>));	
			FuncEventArgsMap.Add(6, typeof(EventFunctionInterceptionArgsImpl<,,,,,,>));
			ActionEventArgsMap.Add(6, typeof(EventActionInterceptionArgsImpl<,,,,,,>));
			ActionInterceptionArgsMap.Add(6, typeof(ActionInterceptionArgsImpl<,,,,,,>));	
			FuncInterceptionArgsMap.Add(6, typeof(FunctionInterceptionArgsImpl<,,,,,,>));							

			FuncExecutionArgsMap.Add(7, typeof(FunctionExecutionArgsImpl<,,,,,,,>));	
			ActionExecutionArgsMap.Add(7, typeof(ActionExecutionArgsImpl<,,,,,,,>));	
			FuncEventArgsMap.Add(7, typeof(EventFunctionInterceptionArgsImpl<,,,,,,,>));
			ActionEventArgsMap.Add(7, typeof(EventActionInterceptionArgsImpl<,,,,,,,>));
			ActionInterceptionArgsMap.Add(7, typeof(ActionInterceptionArgsImpl<,,,,,,,>));	
			FuncInterceptionArgsMap.Add(7, typeof(FunctionInterceptionArgsImpl<,,,,,,,>));							

			FuncExecutionArgsMap.Add(8, typeof(FunctionExecutionArgsImpl<,,,,,,,,>));	
			ActionExecutionArgsMap.Add(8, typeof(ActionExecutionArgsImpl<,,,,,,,,>));	
			FuncEventArgsMap.Add(8, typeof(EventFunctionInterceptionArgsImpl<,,,,,,,,>));
			ActionEventArgsMap.Add(8, typeof(EventActionInterceptionArgsImpl<,,,,,,,,>));
			ActionInterceptionArgsMap.Add(8, typeof(ActionInterceptionArgsImpl<,,,,,,,,>));	
			FuncInterceptionArgsMap.Add(8, typeof(FunctionInterceptionArgsImpl<,,,,,,,,>));							
			
			FuncExecutionArgsMap.Add(9, typeof(FunctionExecutionArgsImpl<,,,,,,,,,>));	
			FuncEventArgsMap.Add(9, typeof(EventFunctionInterceptionArgsImpl<,,,,,,,,,>));
			FuncInterceptionArgsMap.Add(9, typeof(FunctionInterceptionArgsImpl<,,,,,,,,,>));							
		}

		internal static Type MakeGenericArgsType(this Type argumentsType, MethodInfo aspectMember, params Type[] typeArguments) {
			Type type = null;
			int parametersCount = argumentsType.GetGenericArguments().Length;

			if (typeof(IEventFunctionInterceptionArgs).IsAssignableFrom(argumentsType)) {
                type = FuncEventArgsMap[parametersCount];
            }
            else if (typeof(IEventActionInterceptionArgs).IsAssignableFrom(argumentsType)) {
                type = ActionEventArgsMap[parametersCount];
            }
			else if (typeof(IPropertyInterceptionArgs).IsAssignableFrom(argumentsType)) {
                type = aspectMember.HasReturnType() ? typeof(GetPropertyInterceptionArgsImpl<,>) : typeof(SetPropertyInterceptionArgsImpl<,>);
            }
			else if (typeof(IFunctionInterceptionArgs).IsAssignableFrom(argumentsType)) {
				type = FuncInterceptionArgsMap[parametersCount];
			}
			else if (typeof(IActionInterceptionArgs).IsAssignableFrom(argumentsType)) {
				type = ActionInterceptionArgsMap[parametersCount];
			}
			else if (typeof(IFunctionExecutionArgs).IsAssignableFrom(argumentsType)) {
				type = FuncExecutionArgsMap[parametersCount];
			}
			else {
				type = ActionExecutionArgsMap[parametersCount];
			}

			return type.MakeGenericType(typeArguments);
		}

		internal static bool IsFunctionAspectArgs(this Type argumentsType) {
			return typeof(IFunctionExecutionArgs).IsAssignableFrom(argumentsType)||
				   typeof(IFunctionInterceptionArgs).IsAssignableFrom(argumentsType);
		}
	}
}