// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright ©
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------
namespace NCop.Aspects.Extensions
{
    using NCop.Aspects.Engine;
    using System;
    using System.Collections.Generic;

	internal static class EventBindingResolver
	{
		internal static readonly IDictionary<int, Type> ActionBindingMap = null;
		internal static readonly IDictionary<int, Type> FuncionBindingMap = null;
 
 		static EventBindingResolver() {
			FuncionBindingMap = new Dictionary<int, Type>();
			ActionBindingMap = new Dictionary<int, Type>();

			ActionBindingMap.Add(0, typeof(IEventActionBinding<>));				

			ActionBindingMap.Add(1, typeof(IEventActionBinding<,>));	
			FuncionBindingMap.Add(1, typeof(IEventFunctionBinding<,>));	

			ActionBindingMap.Add(2, typeof(IEventActionBinding<,,>));	
			FuncionBindingMap.Add(2, typeof(IEventFunctionBinding<,,>));	

			ActionBindingMap.Add(3, typeof(IEventActionBinding<,,,>));	
			FuncionBindingMap.Add(3, typeof(IEventFunctionBinding<,,,>));	

			ActionBindingMap.Add(4, typeof(IEventActionBinding<,,,,>));	
			FuncionBindingMap.Add(4, typeof(IEventFunctionBinding<,,,,>));	

			ActionBindingMap.Add(5, typeof(IEventActionBinding<,,,,,>));	
			FuncionBindingMap.Add(5, typeof(IEventFunctionBinding<,,,,,>));	

			ActionBindingMap.Add(6, typeof(IEventActionBinding<,,,,,,>));	
			FuncionBindingMap.Add(6, typeof(IEventFunctionBinding<,,,,,,>));	

			ActionBindingMap.Add(7, typeof(IEventActionBinding<,,,,,,,>));	
			FuncionBindingMap.Add(7, typeof(IEventFunctionBinding<,,,,,,,>));	

			ActionBindingMap.Add(8, typeof(IEventActionBinding<,,,,,,,,>));	
			FuncionBindingMap.Add(8, typeof(IEventFunctionBinding<,,,,,,,,>));	

			FuncionBindingMap.Add(9, typeof(IEventFunctionBinding<,,,,,,,,,>));	
		}
	}
}