// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright ©
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------
namespace NCop.Aspects.Extensions
{
	using System;
	using Engine;
	using System.Collections.Generic;

	internal static class MethodBindingResolver
	{
		internal static readonly IDictionary<int, Type> ActionMap = null;
		internal static readonly IDictionary<int, Type> FunctionMap = null;
 
 		static MethodBindingResolver() {
			ActionMap = new Dictionary<int, Type>();
			FunctionMap = new Dictionary<int, Type>();

			ActionMap.Add(0, typeof(IActionBinding<>));				

			ActionMap.Add(1, typeof(IActionBinding<,>));	
			FunctionMap.Add(1, typeof(IFunctionBinding<,>));	

			ActionMap.Add(2, typeof(IActionBinding<,,>));	
			FunctionMap.Add(2, typeof(IFunctionBinding<,,>));	

			ActionMap.Add(3, typeof(IActionBinding<,,,>));	
			FunctionMap.Add(3, typeof(IFunctionBinding<,,,>));	

			ActionMap.Add(4, typeof(IActionBinding<,,,,>));	
			FunctionMap.Add(4, typeof(IFunctionBinding<,,,,>));	

			ActionMap.Add(5, typeof(IActionBinding<,,,,,>));	
			FunctionMap.Add(5, typeof(IFunctionBinding<,,,,,>));	

			ActionMap.Add(6, typeof(IActionBinding<,,,,,,>));	
			FunctionMap.Add(6, typeof(IFunctionBinding<,,,,,,>));	

			ActionMap.Add(7, typeof(IActionBinding<,,,,,,,>));	
			FunctionMap.Add(7, typeof(IFunctionBinding<,,,,,,,>));	

			ActionMap.Add(8, typeof(IActionBinding<,,,,,,,,>));	
			FunctionMap.Add(8, typeof(IFunctionBinding<,,,,,,,,>));	

			FunctionMap.Add(9, typeof(IFunctionBinding<,,,,,,,,,>));	
		}
	}
}