// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright ©
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------

namespace NCop.Core.Exceptions
{	
	using System;
	using System.Runtime.Serialization;

	[Serializable]
	public class DuplicateTypeAnnotationException : ArgumentException
	{
		private static string message = "Duplicate type annotation has been found";
		
		public DuplicateTypeAnnotationException(string message = null) : base(message ?? DuplicateTypeAnnotationException.message) { }

		public DuplicateTypeAnnotationException(Exception innerException) : this(message, innerException) { }

		public DuplicateTypeAnnotationException(string parameterName, string message = null) : base(message ?? DuplicateTypeAnnotationException.message, parameterName) { }

		public DuplicateTypeAnnotationException(string message, Exception innerException) : base(message, innerException) { }

		protected DuplicateTypeAnnotationException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	