// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright © 2013
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace NCop.Core.Exceptions
{
	[Serializable]
	public class DuplicateTypeAnnotationException : ArgumentException
	{
		private static string message = "Duplicate type annotation has been found";
		
		public DuplicateTypeAnnotationException(string message = null) : base(message ?? DuplicateTypeAnnotationException.message) { }

		public DuplicateTypeAnnotationException(Exception innerException) : this(message, innerException) { }

		public DuplicateTypeAnnotationException(string parameterName, string message = null) : base(message ?? DuplicateTypeAnnotationException.message, parameterName) { }

		public DuplicateTypeAnnotationException(string message, Exception innerException) : base(message, innerException) { }

		protected DuplicateTypeAnnotationException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	