//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCop.IoC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCop.IoC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous constructor dependency was found for type {0}. Only one constructor can be annotated with DependencyAttribute attribute..
        /// </summary>
        internal static string AmbigiousConstructorDependency {
            get {
                return ResourceManager.GetString("AmbigiousConstructorDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container is yet to be configured..
        /// </summary>
        internal static string ContainerNotConfigured {
            get {
                return ResourceManager.GetString("ContainerNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve dependent type {0}..
        /// </summary>
        internal static string CouldNotResolveDependentType {
            get {
                return ResourceManager.GetString("CouldNotResolveDependentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve type {0}..
        /// </summary>
        internal static string CouldNotResolveType {
            get {
                return ResourceManager.GetString("CouldNotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register type {0}. An item with the same key has already been added..
        /// </summary>
        internal static string DuplicateRegistrationFound {
            get {
                return ResourceManager.GetString("DuplicateRegistrationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create HttpRequestLifetimeStrategy. HttpContext is null..
        /// </summary>
        internal static string HttpRequestLifetimeStrategyNotSupportedInContext {
            get {
                return ResourceManager.GetString("HttpRequestLifetimeStrategyNotSupportedInContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not auto register type {0}. No parameterless constructor defined for this object..
        /// </summary>
        internal static string NoParameterlessConstructorFound {
            get {
                return ResourceManager.GetString("NoParameterlessConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register interface {0}..
        /// </summary>
        internal static string TypeIsInterface {
            get {
                return ResourceManager.GetString("TypeIsInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow lifetime..
        /// </summary>
        internal static string UnknownLifetime {
            get {
                return ResourceManager.GetString("UnknownLifetime", resourceCulture);
            }
        }
    }
}
