// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright ©
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------

namespace NCop.Mixins.Exceptions
{	
	using System;
	using System.Runtime.Serialization;

	[Serializable]
	public class DuplicateMixinAnnotationException : ArgumentException
	{
		private static string message = "Duplicate mixin annotation has been found";
		
		public DuplicateMixinAnnotationException(string message = null) : base(message ?? DuplicateMixinAnnotationException.message) { }

		public DuplicateMixinAnnotationException(Exception innerException) : this(message, innerException) { }

		public DuplicateMixinAnnotationException(string parameterName, string message = null) : base(message ?? DuplicateMixinAnnotationException.message, parameterName) { }

		public DuplicateMixinAnnotationException(string message, Exception innerException) : base(message, innerException) { }

		protected DuplicateMixinAnnotationException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	