// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright ©
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------

namespace NCop.Mixins.Exceptions
{	
	using System;
	using System.Runtime.Serialization;

	[Serializable]
	public class MissingMixinException : ArgumentException
	{
		private static string message = "Missing mixin annotation";
		
		public MissingMixinException(string message = null) : base(message ?? MissingMixinException.message) { }

		public MissingMixinException(Exception innerException) : this(message, innerException) { }

		public MissingMixinException(string parameterName, string message = null) : base(message ?? MissingMixinException.message, parameterName) { }

		public MissingMixinException(string message, Exception innerException) : base(message, innerException) { }

		protected MissingMixinException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	