// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright ©
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------

namespace NCop.Mixins.Exceptions
{	
	using System;
	using System.Runtime.Serialization;

	[Serializable]
	public class MixinAnnotationException : ArgumentException
	{
		private static string message = "Illegal Annotation exception";
		
		public MixinAnnotationException(string message = null) : base(message ?? MixinAnnotationException.message) { }

		public MixinAnnotationException(Exception innerException) : this(message, innerException) { }

		public MixinAnnotationException(string parameterName, string message = null) : base(message ?? MixinAnnotationException.message, parameterName) { }

		public MixinAnnotationException(string message, Exception innerException) : base(message, innerException) { }

		protected MixinAnnotationException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	