// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright ©
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------

namespace NCop.Mixins.Exceptions
{	
	using System;
	using System.Runtime.Serialization;

	[Serializable]
	public class TypeWeavingException : ArgumentException
	{
		private static string message = "Could not weave a new type. Please see the inner exception.";
		
		public TypeWeavingException(string message = null) : base(message ?? TypeWeavingException.message) { }

		public TypeWeavingException(Exception innerException) : this(message, innerException) { }

		public TypeWeavingException(string parameterName, string message = null) : base(message ?? TypeWeavingException.message, parameterName) { }

		public TypeWeavingException(string message, Exception innerException) : base(message, innerException) { }

		protected TypeWeavingException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	