// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright ©
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------

namespace NCop.IoC
{	
	using System;
	using System.Runtime.Serialization;

	[Serializable]
	public class LifetimeStragtegyException : ArgumentException
	{
		private static string message = "Could not create lifetime strategy within context";
		
		public LifetimeStragtegyException(string message = null) : base(message ?? LifetimeStragtegyException.message) { }

		public LifetimeStragtegyException(Exception innerException) : this(message, innerException) { }

		public LifetimeStragtegyException(string parameterName, string message = null) : base(message ?? LifetimeStragtegyException.message, parameterName) { }

		public LifetimeStragtegyException(string message, Exception innerException) : base(message, innerException) { }

		protected LifetimeStragtegyException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	