

// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright © 2013
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace NCop.IoC
{
	[Serializable]
	public class RegistraionException : ArgumentException
	{
		private static string message = "Type could not be registered";
		
		public RegistraionException(string message = null) : base(message ?? RegistraionException.message) { }

		public RegistraionException(Exception innerException) : this(message, innerException) { }

		public RegistraionException(string parameterName, string message = null) : base(message ?? RegistraionException.message, parameterName) { }

		public RegistraionException(string message, Exception innerException) : base(message, innerException) { }

		protected RegistraionException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	