// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright © 2015
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------

namespace NCop.IoC
{	
	using System;
	using System.Runtime.Serialization;

	[Serializable]
	public class RegistrationException : ArgumentException
	{
		private static string message = "Type could not be registered";
		
		public RegistrationException(string message = null) : base(message ?? RegistrationException.message) { }

		public RegistrationException(Exception innerException) : this(message, innerException) { }

		public RegistrationException(string parameterName, string message = null) : base(message ?? RegistrationException.message, parameterName) { }

		public RegistrationException(string message, Exception innerException) : base(message, innerException) { }

		protected RegistrationException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	