// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright © 2015
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------

namespace NCop.Composite.Exceptions
{
	using System;
    using System.Runtime.Serialization;
	
	[Serializable]
	public class DuplicateCompositeAnnotationException : SystemException, ISerializable
	{
        private readonly string message = string.Empty;
		private readonly bool messageInitialized = false;
		
        public DuplicateCompositeAnnotationException(string message) 
		    : base(message) {
            messageInitialized = true;
        }

        public DuplicateCompositeAnnotationException(string message, Exception innerException) 
		    : base(message, innerException) {
            messageInitialized = true;
        }
		
		public DuplicateCompositeAnnotationException(Type compositeType)
			: base(null) {
			CompositeType = compositeType;
			message = string.Format("Duplicate composition annotations were found for type {0}", compositeType.FullName);
		}
	
		public Type CompositeType { get; protected set; }

		public override string Message {
            get {
                if (messageInitialized) {
                    return base.Message;
                }

                return message;
            }
        }
		
		protected DuplicateCompositeAnnotationException(SerializationInfo info, StreamingContext context)
            : base(info, context) {
			object value = null;

            if (info == null) {
                throw new ArgumentNullException("info");
            }

            message = info.GetString("AttributeMessage");
			value = info.GetValue("AttributeType", typeof(Type));

			if (value != null) {
				CompositeType = (Type)value;
			}
        }

        public override void GetObjectData(SerializationInfo info, StreamingContext context) {
            if (info == null) {
                throw new ArgumentNullException("info");
            }

            base.GetObjectData(info, context);
            info.AddValue("AttributeMessage", Message);
			info.AddValue("AttributeCompositeType", CompositeType, typeof(Type));
        }
	}	
}