// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright © 2014
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace NCop.Aspects.Exceptions
{
	[Serializable]
	public class AspectAnnotationException : ArgumentException
	{
		private static string message = "Illegal annotation exception";
		
		public AspectAnnotationException(string message = null) : base(message ?? AspectAnnotationException.message) { }

		public AspectAnnotationException(Exception innerException) : this(message, innerException) { }

		public AspectAnnotationException(string parameterName, string message = null) : base(message ?? AspectAnnotationException.message, parameterName) { }

		public AspectAnnotationException(string message, Exception innerException) : base(message, innerException) { }

		protected AspectAnnotationException(SerializationInfo info, StreamingContext context) : base(info, context) { }
	}
}
	