// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by NCop Copyright © 2013
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using NCop.Core.Extensions;

namespace NCop.Aspects.Exceptions
{	
	[Serializable]
	public class AspectWeavingException : SystemException, ISerializable
	{
        private readonly string message = string.Empty;
		private readonly bool messageInitialized = false;
		
        public AspectWeavingException(string message) 
		    : base(message) {
            messageInitialized = true;
        }

        public AspectWeavingException(string message, Exception innerException) 
		    : base(message, innerException) {
            messageInitialized = true;
        }
		
		
		public override string Message {
            get {
                if (messageInitialized) {
                    return base.Message;
                }

                return message;
            }
        }
		
		protected AspectWeavingException(SerializationInfo info, StreamingContext context)
            : base(info, context) {

            if (info == null) {
                throw new ArgumentNullException("info");
            }

            message = info.GetString("AspectWeavingMessage");
        }

        public override void GetObjectData(SerializationInfo info, StreamingContext context) {
            if (info == null) {
                throw new ArgumentNullException("info");
            }

            base.GetObjectData(info, context);
            info.AddValue("AspectWeavingMessage", Message);
        }
	}	
}